### ISSUE TITLE
mpv don't close when my application close

### ISSUE THREAD

**Issue by zyk-miao** [bleonard252/just_audio_mpv#4]
mpv don't close when my application close

**Comment by bleonard252** [comment]
This is a known issue and not one that's feasible to solve. Flutter doesn't dispatch any shutdown events so nothing knows to stop; therefore, since MPV is running in the background separately, it doesn't know when to stop. A good way to work around this is to use a package like `window_manager` to add a step when closing your app that tells `just_audio` to stop. You can see [Bodacious](https://github.com/bleonard252/bodacious/blob/bdd5c6f987a79f42c805bd16dfeaaa3510f7c3bb/lib/main.dart#L292) for an example of how this is done.
